### ISSUE TITLE
When Expression takes more then 1 line it isn't included in coverage report

### ISSUE THREAD

**Issue by zhiburt** [xd009642/tarpaulin#1009]
**Describe the bug**

Hi

I've noticed when the line is too long and cargo fmt put's it on a new one we don't have a proper report.

![Screenshot_2022-05-14_14-16-27](https://user-images.githubusercontent.com/20165848/168423423-663c718a-7f26-4884-bb7c-6de80cf9a31f.png)

![Screenshot_2022-05-14_14-22-03](https://user-images.githubusercontent.com/20165848/168423555-2d6300a2-4a14-4385-8705-3e4c9c9b2e3f.png)

I think 2 and 3 lines must be covered correspondingly?

Debug tarpaulin file `debug/tarpaulin/crate-name-tarpalin.json` doesn't contains this line too.

Sorry if it's a duplicate.

**Comment by xd009642** [comment]
So this makes sense if you think of the fact the line coverage is also grouping things by expressions. The first line the expression is on is a "logical line" (term from tarpaulin code). After all formatting changes that split the same code over multiple lines shouldn't change the coverage statistic. Having a way to show this better in the HTML report could be nice, but adding the other related lines to the output json would change percentages in the end report which isn't desirable imo.

After all, it would be really annoying to see coverage dramatically change because someone ran `cargo fmt` and then suddenly fail to meet a threshold in CI because what was 1 uncovered line in the 2nd example has turned into 5
