### ISSUE TITLE
Calling `launch_tarpaulin` from within `cargo tarpaulin` fails?

### ISSUE THREAD

**Issue by jeremydavis519** [xd009642/tarpaulin#104]
In order to test the [`runtime-macros`](https://crates.io/crates/runtime-macros) crate, I had it use `launch_tarpaulin` and check the line coverage inside the test case, since I needed to make sure the procedural macro's code was actually running. That test case works without any problems when it's run through `cargo test`.

However, when it's run through `cargo tarpaulin`, I get this output:

```
        Building project
Unexpected signal when starting test
Error when starting test: ECHILD: No child processes
Unexpected signal when starting test
Error when starting test: ECHILD: No child processes
```

(That's followed by the test case failing because Tarpaulin didn't record any lines of code being executed in the child process.)

I haven't worked much with Linux signals, and I wasn't able to find any part of that error message online, so I have no idea what the actual cause is, but it seems to have something to do with running Tarpaulin through itself.

Apart from being unable to use `launch_tarpaulin`, the use of `cargo tarpaulin` works as expected. It accurately counted all the lines of code that executed in the crate where I used it.

**Comment by xd009642** [comment]
So this is down to https://github.com/xd009642/tarpaulin/issues/44, essentially tarpaulin listens for child signals to show when things happen it needs to handle like thread spawning/destruction, tests starting/ending and source lines being hit. 

From my previous investigation of the issue what I observed was as follows. The outermost tarpaulin is listening for everything below it including what the innermost tarpaulin is tracing and then stealing what's meant for the inner tarpaulin which finds it's test disappears as a result and when it tries to start it's test it finds the child process doesn't exist anymore.

It's a bit of a tricky one to fix and requires getting more intimate with parts of ptrace that aren't particularly well documented and lack existing example code. Also, it was something no one actually needed apart from me to run tarpaulin on tarpaulin. Because of that, I ended shelving it temporarily to focus on issues more important to users.

To get around this without #44 being fixed you could see if there's way to launch tarpaulin on the folder as a separate process which doesn't have a child PID with the verbose flag set and try and pipe in the output into a string and parse it to verify it.. That might work, I'm not sure tbh.

**Comment by jeremydavis519** [comment]
Alright. It's not a big deal for runtime-macros either. I just wanted to make sure you were aware that it was happening.

**Comment by xd009642** [comment]
Cool, as long as it doesn't cause issues. I'm going to close this as a duplicate but when #44 is solved I'll ping you if I remember.
