### ISSUE TITLE
Use a different target dir by default

### ISSUE THREAD

**Issue by Plebshot** [xd009642/tarpaulin#1086]
Having stumbled upon #1076, I feel like using a separate target directory should be the default for tarpaulin. We've also dealt with a lot of confusion why our pipeline is so painfully slow despite caching. It can be really confusing if a simple `cargo check` suddenly recompiles everything because tarpaulin overwrote the cache with a different build.

This behavior was even more unexpected to me, when it recompiled everything despite the `--skip-clean` flag. Originally I came her to open a bug report for that, but now understand that sometimes tarpaulin needs to recompile everything due to rustflags.

I think having a separate target dir by default would prevent a lot of this initial confusion, especially for people not knowing much about rustflags etc.

**Comment by xd009642** [comment]
So I don't think setting a different target directory by default is desired, looking at some of my projects the target dir is already >3GB from a clean build and the vast majority of tarpaulin users are using it in CI and the cleaning behaviour doesn't actually matter to them (this won't change CI runtime after all). 

Also when #549 becomes default and the RFC for limiting rustflags to just the workspace crates drop the situation will dramatically improve anyway so I'd rather wait till then instead of bloating up peoples target directories more by default.

**Comment by Plebshot** [comment]
That's some valid points. I hope it improves with that RFC in the future then.

In my experience, caching in pipelines is always preferred (unless building release) to avoid having the devs sit for 40min to realize something failed. The current behavior just caused massive confusion for us. I noticed that even locally, in between running tarpaulin, my IDE runs `cargo check`, therefore rebuilding the entire project everytime.

**Comment by xd009642** [comment]
To make it more default, you can add a `tarpaulin.toml` config file setting a target dir for tarpaulin to use and have it as a project template. That will cause less confusion in new projects with other engineers

**Comment by Plebshot** [comment]
Yes, we solved it now by adding a target dir manually. Depending on how long #549 will actually take, it would be nice if this behavior with the flags could be pointed out in the docs. Especially with `--skip-clean` it's irritating if the project recompiles everytime due to running `check` etc. in between.

**Comment by eliphatfs** [comment]
Sorry to bump the thread, but I just went into tarpaulin from llvm-cov today and I think the default settings are unusable due to the recompilation in dev space. cargo check reruns for 5 minutes then tarpaulin runs for another 5 minutes and i can do nothing during the time. I then tweak a few lines of code to cover a missed case and wait 10 minutes again. In comparison, 3GB is just a common number for modern storage -- Actually, llvm-cov defaults to another target directory. I think we should at least add the interaction with cargo-check in README.
