### ISSUE TITLE
Tarpaulin reports 0 coverage with rustc 1.27.0-beta.1 and nightly

### ISSUE THREAD

**Issue by fafhrd91** [xd009642/tarpaulin#109]

**Comment by xd009642** [comment]
So I just tried tarpaulin on my own pc with the latest nightly and it reported coverage correctly. Could you give me some more details i.e. what distro you're on, example project and tarpaulin verbose output?

**Comment by xd009642** [comment]
I've cracked it! Essentially rust somewhere has optimised the code that's generated and removed unnecessary `push %rbp; mov %rsp, %rbp" from the start of functions and probably some other things. But this has the knock on effect of changing the minimum address assigned to a line at the start of a function causing it to class with the minimum address for the test function that calls it. 

Tarpaulin didn't gracefully handle conflicting instrumentation points tied to different lines because they were never something I'd encountered before. So now I've got it checking for said conflicts and discard the clashes so there's only one instrumentation point per address and that's fixed it.

Just need to sort this out in the reporting state to remove false negatives and then this will be ready to merge into develop!

**Comment by fafhrd91** [comment]
great!

**Comment by xd009642** [comment]
Right it's fixed and merged into develop. Because of my latest updates to the source code analysis module to install from the latest develop you need to do `RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin --git https://github.com/xd009642/tarpaulin --branch develop` :+1:

**Comment by fafhrd91** [comment]
thanks!
