### ISSUE TITLE
No coverage report generated after following the README

### ISSUE THREAD

**Issue by djc** [xd009642/tarpaulin#111]
I'm trying to use tarpaulin for the first time with Travis for one of my projects, but despite more or less exactly following the example config from the README, no coverage report seems to be produced:

https://github.com/djc/quinn/compare/coverage
https://travis-ci.org/djc/quinn/jobs/383049897

Any hints? I hope I'm not doing anything too silly...

**Comment by xd009642** [comment]
Ah glad this is sorted. And yes I'm working to get the next release out just trying to figure out if it's possible to publish to crates.io given the rust flag used to build and get one last feature in.

Also, a lot of changes have happened to testing stability just to be confident it's all good!

I'll close this issue since you've sorted it :+1:

**Comment by djc** [comment]
Well, it's awfully slow right and wasteful to rebuild tarpaulin for every build. So having a release would be much better.

**Comment by xd009642** [comment]
There are docker releases of the latest develop branch! The readme goes into more detail

**Comment by djc** [comment]
I tried that, but it fails in a non-obvious way:

https://travis-ci.org/djc/quinn/jobs/383610281
https://github.com/djc/quinn/commit/28ede23d967e34e76d3fa0d569be36ed2e2ff37b

**Comment by xd009642** [comment]
Interesting that looks like the same issue as #23 xd009642/tarpaulin:develop should work for you as latest is 0.5.6 anyway so falls foul of the nested import issue!

**Comment by djc** [comment]
Still fails the same way as in #23.
