### ISSUE TITLE
Make it possible to ignore path that lead to a panic!()

### ISSUE THREAD

**Issue by vberger** [xd009642/tarpaulin#115]
In some cases we have some `panic!()` or `unreachable!()` which are basically asserts. Stuff like:

```rust
match foo {
    Bar::Meh => { ... },
    Bar::Moo => { ... },
    Bar::Maa => {
        // this one cannot happen at this point!
        unreachable!()
    }
}
```

It would be nice to have an option so that tarpaulin does not mark the last branch as uncovered by the tests, as it's kind of the point that it should *not* be coverable.

**Comment by sharksforarms** [comment]
You could test that path using the `#[should_panic]` attribute

https://doc.rust-lang.org/book/second-edition/ch11-01-writing-tests.html#checking-for-panics-with-should_panic

**Comment by xd009642** [comment]
So `unreachable!`, `unimplemented!` and `include!` themselves should be ignored. The block around it may still be in the coverage results just because other things could be there including early returns. 

One potential solution I think would work would be

```
match foo {
    Bar::Meh => { ... },
    Bar::Moo => { ... },
    Bar::Maa => unreachable!()
}
```

I'm not sure about ignoring panics! as users creating binaries may use panics to early abort during error conditions that could occur. Maybe putting it behind a flag... I'll have a think!

**Comment by vberger** [comment]
About `unreachable!()`, I guess there are still some bugs then? See on the report: https://codecov.io/gh/Smithay/wayland-rs/src/master/wayland-scanner/src/util.rs#L38

Other than that, I'd certainly love having a flag (or maybe some annotation in the source ?) that would allow me to specify that panics don't need to be covered for a given crate.

See, my use case is for my wayland-scanner crate. The parser expects an input XML file with a certain structure, and just panics if the input is ill-formed. I'm not really interested in its behavior on ill-formed files, as these wayland protocol files are not numerous, and largely shared & validated already.

And, I'm not very thrilled about the idea of creating ~20 ill-formed protocol files just to `#[should_panic]` test these. So being able to have `panic!(..)` be treated the same as `unreachable!()` would allow me to remove all this useless information and quickly evaluate which parts of my parser are indeed not tested.

**Comment by xd009642** [comment]
That is a bug! I'll add a test and get to the bottom of it. And I could add a `--ignore-panics` flag for that use case. 

On a related note, if you use latest develop there's now a way to use `cfg_attr`s to ignore modules, functions, methods, impl blocks and traits. I don't go into finer blocks than that because I think at that point it's getting a bit noisy - but it may be of interest! Also, I'm planning on releasing more frequently than I have so expect to see a 0.6.1 by the end of next week :smile:

**Comment by xd009642** [comment]
So this is now on the latest develop. `--ignore-panics` is a new option added. 

The other issue with the `unreachable!` macro not being hit was also fixed. Unlike in syntex where the internals of the visitor trait traversed the syntax tree deeper, in syn I have to do that myself. So I added code that takes any expression with a block that wasn't traversed deeper and went into the block.
