### ISSUE TITLE
Tarpaulin stealing signals

### ISSUE THREAD

**Issue by vorner** [xd009642/tarpaulin#12]
I have a test that checks handling of SIGTERM and shutting down of an event loop. This is what I get when running the test under tarpaulin:

```
test reactor::tests::signal ... Unexpected signal SIGTERM
test reactor::tests::signal has been running for over 60 seconds
```

It seems tarpaulin eats the signal for itself and the test doesn't get it.

This is the [test in question](https://gitlab.labs.nic.cz/turris/pakon-aggregator/blob/9a6fa9caf31f94d470dcea3397460dbba813129b/src/reactor/mod.rs#L314). Should I try creating a smaller case?

**Comment by xd009642** [comment]
So tarpaulin instruments your code with soft breakpoints and uses SIGSTOPs to find what lines have been hit. Since tests cause a bunch of new thread ids to be spawned I adopt a greedy listening approach. 

Looking at the posix documentation I haven't found a way to not consume a signal and in the event my instrumentation or the test actually emits a SIGTERM for other reasons I'm not sure if that would be wise.

One workaround would be to add the ignore attribute to any tests that raise signals. Not very good if you have a lot of tests that raise signals though. I'm going to look through the posix documentation and try and find a better solution to this.

**Comment by vorner** [comment]
Right, that doesn't sound like a nice workaround, because the ignore attribute is meant for some other things, I guess. I do want to run the test as part of the normal testing.

I haven't looked into the instrumentation, so I don't know if it is possible, but would it be possible to limit the signals you listen to? Or, if you get a signal you don't expect, forward it further? There must be a way how other tools do this.

**Comment by xd009642** [comment]
That's what I'm looking into now, I've got a few avenues to pursue and some different ideas. I'll keep you updated but I can't promise this will be a super quick fix.

**Comment by xd009642** [comment]
So tarpaulin uses a breakpoint method of instrumenting code, so to see if gdb could handle an inferior process which emitted a sigterm I ran your test executable with gdb and got this output `Thread 16 "reactor::tests:" received signal SIGTERM, Terminated.` when it attempted to run the test in question. 

However, if I stepped over the signal emission it worked although 2 tests failed at the end that didn't previously fail (signalled test not being one of them). Possibly due to signals being stolen by gdb. Either way it's not exactly encouraging that GDB doesn't handle this use case particularly well either, although that may just be a design decision.

**Comment by vorner** [comment]
It is possible the other tests failed because of timing issues (some of them test interaction between timeouts, etc), as gdb stops the whole program when waiting for user input. If I run it in gdb with `r --test-threads 1`, it stops on that one test, continues and then all tests pass, which would support the timing issue theory.

It seems it stops the process when whatever signal arrives, but then forwards the signal to the process when continued. I believe this could be done by tarpaulin as well (without waiting for the user's consent to continue).

**Comment by xd009642** [comment]
Hi @vorner I solved the issue for signals other than SIGSTOP and SIGTRAP which tarpaulin relies on and it now runs through your tests. However, testing on your repo it reports 0% coverage. I think this might be due to the asynchronous code or other processes but I haven't yet had a chance to look at it in any depth. I'll open a new issue and tag you in it to tackle this next problem :+1:

**Comment by vorner** [comment]
Thanks, I can confirm it now passes.

**Comment by xd009642** [comment]
Great to hear, also you might want to consider getting turris added to [friends of rust](https://www.rust-lang.org/en-US/friends.html) :+1:

**Comment by vorner** [comment]
Thanks for the suggestion, I plan on doing that once we actually ship some rust code :-).
