### ISSUE TITLE
Add Unsafe Coverage

### ISSUE THREAD

**Issue by insanitybit** [xd009642/tarpaulin#124]
Hey, I think it would be really neat if there were stats on unsafe block coverage. Instead of the output looking like:
```
87.06% coverage, 74/85 lines covered
```
It would look like (making it up)
```
87.06% coverage, 74/85 lines covered
72.22% unsafe coverage, 13/18 unsafe block lines covered
```

Or something along those lines.

The assumption is that unsafe code is trickier than safe code, and worth calling out in regards to test coverage. A lot of discussion has been had around how to surface the usage of unsafe blocks in crates, and test coverage for the code seems like decent signal for 'yes, unsafe exists, but we keep an eye on it'.

What do you think?

P.S. Thank you for building this, it's a very cool project that I use personally.

**Comment by Shnatsel** [comment]
Line coverage is a fundamentally wrong way to measure coverage of unsafe code. You could have 100 valid PNGs that cover every single bit of a PNG parser, 100% coverage of all its `unsafe` blocks and completely miss a devastating security vulnerability caused by a trivial malformed input that sets a single length field to a deliberately incorrect value.

So "we have unsafe code but it's 100% covered by tests" where "100% coverage" means "100% lines of it are reached by tests" would only create a false sense of security. Measuring coverage here is **not** the right tool for the job.

To verify that unsafe code is exhaustively tested you need to list all possible paths through the code that can be taken and measure how many of the possible paths are actually exercised. This is called "[symbolic execution](https://en.wikipedia.org/wiki/Symbolic_execution)". Sadly, the existing tools for it are not integrated with Rust yet: KLEE integration for Rust is [discontinued](https://github.com/jawline/klee-rust) and [SAW](https://saw.galois.com/) never had it in the first place.

In the meantime, a reasonable way to deal with unsafe blocks would be continuous fuzzing, e.g. in a CI task, when coupled with address sanitizer and/or memory sanitizer. Rust actually has _excellent_ support for fuzzing - see [cargo-fuzz](https://github.com/rust-fuzz/cargo-fuzz), [afl.rs](https://github.com/rust-fuzz/afl.rs) and [honggfuzz.rs](https://github.com/rust-fuzz/honggfuzz-rs). Most of them have sanitizer support built-in. Sadly, fuzzing will not discover bugs that require more than one byte set to a crafted value to trigger them.

**TL;DR:** please do not use line coverage to make assumptions about unsafe code.

**Comment by xd009642** [comment]
So @Shnatsel raises a lot of good points about shortcomings of line coverage for testing like this. There is potential for other more advanced coverage types like [MCDC](https://en.wikipedia.org/wiki/Modified_condition/decision_coverage) to be of use with assessing how tested unsafe code is (but even then it has issues). 

When I get that far into coverage I might revisit this as an idea but for now while I just have line coverage I think this might create a false sense of security.

**Comment by insanitybit** [comment]
I wasn't really implying *limiting* to line coverage, but as it's the only thing provided at the moment, that's what would exist.
