### ISSUE TITLE
Get error `ASLR disable failed: EPERM: Operation not permitted` when executing `cargo tarpaulin -v`

### ISSUE THREAD

**Issue by new-commer** [xd009642/tarpaulin#146]
I use root user , and get the error `ASLR disable failed: EPERM: Operation not permitted` when executing `cargo tarpaulin -v`. And i tried `sudo cargo tarpaulin -v` , it prompt `cargo command not found` 
So i tried `sudo -s cargo tarpaulin -v` , it also prompt `ASLR disable failed: EPERM: Operation not permitted` .How can i resolve it ?

**Comment by xd009642** [comment]
So what environment are you running in? A CI server (if so which one) or your personal machine? This issue is a duplicate of #77 so you may find help there. ASLR is a security measure to stop malicious processes inspecting the memory or altering the execution of a process (including arbitrary code execution). So you may need to change a security rule via seccomp to allow tarpaulin to disable ASLR. 

As for how to do that I'm not sure but maybe running tarpaulin with `setarch -R` will work

**Comment by new-commer** [comment]
Btw , why `Tarpaulin` can run in personal machine(centos system ) , just use normal user which have no `sudo` authority (So it have no authority  to disable ALSR).
And do not work in docker , even though use root user ?

**Comment by xd009642** [comment]
@new-commer Have you tried the method in the docker section of the readme? And has it solved your issue?

**Comment by new-commer** [comment]
@xd009642 thanks Thank you for your help ， we have tried it works  . And We're trying to do that in gitlab-ci .

**Comment by gdesmott** [comment]
@new-commer : did you find any way to make this work with gitlab-ci? I'm hitting the same problem.

**Comment by xd009642** [comment]
You might be able to get it to work using the docker image in gitlab.
Although I tried it myself on a test project last weekend and it worked
fine (using tarpaulin version 0.9.1)

**Comment by ThibsG** [comment]
Hi, just to help if someone is experiencing same issue using a custom built image for the runner.

You can also add `security_opt` option to your runner configuration file `/etc/gitlab-runner/config.toml`:

```toml
[[runners]]
  [runners.docker]
    security_opt = ["seccomp:unconfined"]
```

Then restart gitlab-runner service in order to reload configuration.

Note that as said in other issues this option can also be used when running a container by hand:
`docker run --rm -it --security-opt seccomp=unconfined ...`

It could be interesting to add this to a Wiki/FAQ page.

**Comment by rye** [comment]
Just to provide more background for people in situations where `seccomp=unconfined` is too liberal, one can also use a modified seccomp profile that is used. [Per the Docker documentation on `seccomp`](https://docs.docker.com/engine/security/seccomp/), a number of syscalls are restricted through the default seccomp policy, including the `personality` syscall which is how `tarpaulin` and other tools that require ASLR to be disabled can request so.

Docker's built-in [default](https://github.com/moby/moby/blob/master/profiles/seccomp/default.json) seccomp policy _does_ allow the use of the `personality` syscall in [certain cases](https://github.com/moby/moby/blob/4f8070c84d568a64fe34b91fc8a8ebc33f6600db/profiles/seccomp/default.json#L386-L470), but only with the arguments `0x8`, `0x2_0000`, `0x2_0008`, and `0xffff_ffff` (`GET_PERSONA`), apparently.

The current method of disabling ASLR does not match one of the requested values, so is rejected by the kernel:

https://github.com/xd009642/tarpaulin/blob/c5e8e09c130cf202e399b3716e187e65f60291bd/src/process_handling/linux.rs#L35-L43

All of this is to say that one could add the object

```json
{
  "names": [
    "personality"
  ],
  "action": "SCMP_ACT_ALLOW",
  "args": [
    {
      "index": 0,
      "value": 262144,
      "valueTwo": 0,
      "op": "SCMP_CMP_EQ"
    }
  ],
  "comment": "Enable personality(ADDR_NO_RANDOMIZE) syscall",
  "includes": {},
  "excludes": {}
}
```

to the `syscalls` key in their seccomp JSON file to allow ASLR disables to succeed. (If the persona is somehow different than just `0`, the `"value"` might need tuning.)
