### ISSUE TITLE
Improvements when using tarpaulin and editions

### ISSUE THREAD

**Issue by marcelbuesing** [xd009642/tarpaulin#156]
I just ran into the following error:
```
cargo tarpaulin -v       
Error during run
```
Version:
`cargo-tarpaulin version: 0.6.8`

OS:
`Linux x op 4.17.14-arch1-1-ARCH #1 SMP PREEMPT Thu Aug 9 11:56:50 UTC 2018 x86_64 GNU/Linux`

rustc:
`rustc 1.31.0-nightly (77af31408 2018-10-11)`

Reproduce by creating a new project using nightly:
```
cargo +nightly new foo
```

I noticed that when removing the `edition = "2018"` in the Cargo.toml tarpaulin works without problems.

**Comment by xd009642** [comment]
You need cargo-features = ["edition"] at the top of your Cargo.toml. I've had this raised last week to me and the error messaging on develop is better now so when that comes out it'll be clearer.

I'll probably add something to the README as well!

**Comment by marcelbuesing** [comment]
Ah great! Should have searched the closed issues. Thank you =)!:

**Comment by xd009642** [comment]
So I'm traveling so realistically won't get to do this until around Friday. If sometime wouldn't mind doing a PR adding a "Using with Editions" subsection after installation I can approve it I'd be grateful (and do it on master so it's visible to users)

**Comment by xd009642** [comment]
So the code the checks for this feature is all in the cargo dependency, I just work off the `Result<_,_>` types it's functions output. So it'll be down to how I'm using cargo as a library. Unfortunately parts of it aren't well documented because the vast majority of users are using it as an executable not a library. 

If anyone can help with the cargo thing that would be better than the README change for sure! I'm just going to reopen this issue as it's clearly not yet resolved.

**Comment by Cogitri** [comment]
Uhh...at least for me this works without putting cargo-features into my cargo.toml.

**Comment by xd009642** [comment]
Just tested following the 2018 edition being stabilised cargo-features is no longer required. So I'm closing this issue
