### ISSUE TITLE
Make coveralls api integration an optional feature

### ISSUE THREAD

**Issue by sosthene-nitrokey** [xd009642/tarpaulin#1582]
Today there is no way to disable the coveralls integration when compiling tarpaulin.

This features is the only reason that `openssl` needs to be brought in. Openssl is one of the main pain points when attempting to compile cargo tarpaulin. 

For some reason even with the `vendored-openssl` feature enabled, tarpaulin still relies on a dynamically linked openssl1.1 when building in a docker container. Being able to disable the coverall API integration which we do not need would make this problem go away.

**Comment by xd009642** [comment]
I've just pushed out a potential fix for this, if you have some time to test it to make sure it works for your use case https://github.com/xd009642/tarpaulin/pull/1583 

And I think the vendored openssl feature thing might be because of libgit? I know that's one of the users of openssl in the dependency tree

**Comment by xd009642** [comment]
Ah never mind I did my cargo check without excluding the feature :facepalm: still some stuff to change

**Comment by xd009642** [comment]
okay that should work now for you :pray:

**Comment by xd009642** [comment]
Release pipeline has been initiated so provided it all goes smoothly there should be a new version in under an hour with the ability to remove coveralls from the install
