### ISSUE TITLE
"Unexpected stop" when running with tarpaulin

### ISSUE THREAD

**Issue by mathstuf** [xd009642/tarpaulin#21]
Not sure what's up here. When testing [`git-workarea`](https://gitlab.kitware.com/utils/rust-git-workarea) using tarpaulin, I see it testing `test_gitdir`, saying "Unexpected stop" and then quitting. However, the binaries are still running (`test test::test_gitdir has been running for over 60 seconds`).

**Comment by xd009642** [comment]
Interesting I'll have a look at that tonight and get back to you either today or tomorrow

**Comment by yodaldevoid** [comment]
I have seen this (or something similar) when a test spawns a child process.

**Comment by xd009642** [comment]
Yeah I found it's due to a fork in the code. Think I have a nice solution just need to test it

**Comment by xd009642** [comment]
Quick update, my solution for the fork wasn't enough to fix the issue because the launching of a command actually results in a exec event. This causes issues with ptrace because it appears that the current thread has exited (which is the runner thread for the test) and tarpaulin currently interprets this as the test function finishing.

**Comment by xd009642** [comment]
Just a quick update, this is a fairly complicated ptrace behaviour as the git calls cause an exec to be called. This means that the process exits and a new process is created with the same PID running the git command. This results in what appears as a zombie process in ptrace so will require a fair bit of effort to remedy and test to make sure it doesn't impact existing functionality. Still working on it though!

**Comment by mathstuf** [comment]
Hmm, how does `gdb` do it? The `strace` codebase may be easier to use though since following the logic from the `-f` flag is probably easier there.

**Comment by xd009642** [comment]
So I've been using strace as a frame of reference for some of the ptrace things mainly because the gdb source is definitely a lot more arduous to follow. Ptrace is quite a complicated system call as there's this implicit state machine that imo isn't very well documented. So I'm looking to the [strace guide on ptrace](https://github.com/strace/strace/blob/a58fc3c95032a4ee7bb5d5ded3a8ff3ef14076fb/README-linux-ptrace) namely the section execve under ptrace. 

Also given the complexity I want to make sure I test this quite thoroughly.

**Comment by xd009642** [comment]
I (via strace), may have cracked this one! I spotted they detach the forked child to let it exec so I'm adding that into the loop! Hopefully this may be not too hard after all :smile:

**Comment by mathstuf** [comment]
Cool. It may be worth adding an `-f` flag to follow children if possible too. Not all `fork` calls lead to an `exec` (though I don't know that Rust exposes `fork` directly, so maybe it's not an issue after all).

**Comment by xd009642** [comment]
Yeah I'll add it to the enhancement list. As it stands my current release should be enough for tarpaulin to work for your project so I'll release it without following and add that in a later release :+1:

**Comment by mathstuf** [comment]
Cool, thanks. I'll test it out :) .

**Comment by xd009642** [comment]
It's 0.3.12, I'm publishing it now so it should be up on crates.io in 5-10 minutes hopefully

**Comment by mathstuf** [comment]
Building from `git` already right now ;) .

**Comment by mathstuf** [comment]
Hmm. Seems this isn't completely fixed. It looks like `Cargo.lock` still says `0.3.11` and is breaking `cargo install` from `crates.io` versus from git.

**Comment by mathstuf** [comment]
These crates:

  - https://gitlab.kitware.com/utils/rust-git-ghostflow
  - https://gitlab.kitware.com/utils/rust-git-checks

also timeout even building `cargo-tarpaulin` from git. These use `rayon` and seem to be failing on tests which use it.

**Comment by xd009642** [comment]
Looks like I messed up the publish some how... I'll yank 0.3.12 and release 0.3.13... Bit hacky but I think it's the only fix. I'll look at the Rayon stuff as well

**Comment by xd009642** [comment]
Rayon I know the issue. New threads cause clones not forks. Previously the only clones I handled was spawning a single thread to run a process as that's what rustc-test does when it launches a test. However, threads are often used to run the same function multiple times in parallel. This means by state tracking for breakpoints needs to take into account the pid and the state. 

This will probably be a reasonable sized change but I should hopefully have an initial version done by tonight

**Comment by mathstuf** [comment]
Cool, thanks for the quick fixes.

**Comment by xd009642** [comment]
No problem, I've already prototyped it and it works on small programs but there's a race condition of some sort present which is more likely to hit the more threads evaluate a function. I've got it on a feature branch so when I think I've solved that race condition I may push it and ask if you can test it installed from git :+1:

**Comment by xd009642** [comment]
Right so it works on the test some of the time. Occasionally however it gets stuck and leaves early (although it reports the coverage it had up to that point).

A lot of this is due to dealing with the fact the ELF file is essentially a single data source (where data is the instructions the program is running). I'm modifying the instructions to add instrumentation and the threads are reading the instructions. So I've kind of got to implement thread synchronisation/locks in my event loop :disappointed:.

Good news is that it works some of the time, so I'm at least getting closer. So you're free to try it out from the latest commit in the thread_support branch

**Comment by mathstuf** [comment]
Thanks; that's at least better than hanging forever (it just ending when it does crash).

**Comment by xd009642** [comment]
Better, but not yet perfect! Hopefully I can crack the last little issue and when I'm happy there'll be another release

**Comment by xd009642** [comment]
So tarpaulin now behaves the same each time. Essentially, the issue before was if one thread tried to run an instruction while I was removing or adding the instrumentation point back in it caused a segfault. One solution would be to stop all threads in the process via a kill call, however the same behaviour existed but more sporadically. 

In the end I've gone for the solution of detecting the thread count and not re-enabling the instrumentation breakpoints if there are multiple threads in the test or code being tested. This means the hit count won't be accurate but I print a warning and the hit count had inaccuracies anyway based on how many instructions can possibly map to a line. Also, stability and the correct hit percentage are definitely more important :smile:.

Sorry it's taken so long, this one was a bit tricky

**Comment by xd009642** [comment]
Oh also it's being published in 0.4.1 so no more needing to install a version from a git branch!
