### ISSUE TITLE
0.8:latest Docker build fails

### ISSUE THREAD

**Issue by Eraden** [xd009642/tarpaulin#229]
Fail to compile on CircleCI, image `abronan/rust-circleci:latest`

System:
* rustup 1.18.3 (435397f48 2019-05-22)
* rustc 1.32.0-nightly (edaac35d6 2018-11-24)
* cargo 1.32.0-nightly (b3d0b2e54 2018-11-15)

```
imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-tarpaulin-0.8.0/src/process_handling/mod.rs:5:9
  |
2 | pub mod linux;
  | -------------- not an extern crate passed with `--extern`
...
5 | pub use linux::*;
  |         ^^^^^
  |
```

**Comment by xd009642** [comment]
1.32 is a pretty old version and looking at the error referenced in the error message it seems to be something that's currently been stabilised (we are on 1.34 on stable and 1.36 on nightly). Is there a chance you could update the rustc version in the image? Or see if the owner of the image can?

**Comment by Eraden** [comment]
I'll try today and paste the result.

**Comment by rye** [comment]
@Eraden, did this get fixed?

**Comment by xd009642** [comment]
So since tarpaulin was nightly only at that stage and only went to a crate that worked on stable fairly recently so I don't offer any backwards compatible support for those older compilers. I'm going to close this but if you have the same problem with a >1.33 compiler feel free to reopen the issue @Eraden
