### ISSUE TITLE
Keep instrumentation enabled on tests with multithreading.

### ISSUE THREAD

**Issue by xd009642** [xd009642/tarpaulin#35]
From #21 instrumentation was disabled after it was first hit when the test or function tested contained multi-threaded code. This prevented a race condition with ptrace pokes, but disrupts the hit count.

The hit count isn't too meaningful a statistic so it's low priority, however this is necessary for decision or condition coverage so will need to be sorted for that.

**Comment by philipc** [comment]
I had a look at the current code for handling threads, and I don't really understand what it is doing. It looks like it is trying to keep an `is_running` state for each breakpoint per thread, but I don't think you can do that because threads share they same code page, so they all have the same breakpoint status. Maybe you should be indexing `is_running` by TGID instead of TID.

**Comment by xd009642** [comment]
You're 100% right on what the code is doing! And thanks for that tip, I'll admit I'm still learning about some of the intricacies of TIDs and TGIDs. 

I'll look into this at some point, just got some issues I'm working on right now that I'd like to finish before I move onto other tasks :+1:

**Comment by mathstuf** [comment]
FWIW, using `RAYON_NUM_THREADS=1` helps a lot here for crates using Rayon at least.

**Comment by mathstuf** [comment]
Ping @xd009642 Any luck with the TGID/TID stuff?

**Comment by xd009642** [comment]
Nope no luck at all, I got stuck and decided to shelve it for now. Unless anyone else has any bright ideas!

**Comment by xd009642** [comment]
Closed, the solution for #190 fixed this issue
