### ISSUE TITLE
"competition" with IDE integration for checks

### ISSUE THREAD

**Issue by mathstuf** [xd009642/tarpaulin#383]
I'm using ALE for Vim which ends up running `cargo check` in the background. Whenever this happens, `cargo tarpaulin` ends up having to rebuild the entire dep tree. Is there some way to make these not conflict so much?

**Comment by xd009642** [comment]
I guess it would be because the rustflags variable differs for tarpaulin runs, so if you get ALE to use the same rustflags that should fix it.

You might need to set up that rustflags so it's just for ALE I'm not sure if rustc/cargo are smart enough to spot variables duplicated in the rust flags or just see the string is different and reruns because tarpaulin can result in things being there twice! 

When I'm on my pc I'll post up the rustflags, otherwise on master they should just be in src/lib.rs

**Comment by colvin** [comment]
I'm having this same issue. `cargo check`, `cargo build`, `cargo test` all conflict with tarpaulin, and require full rebuilds when switching between any of the former and tarpaulin.

I'm also using ALE under Vim, and this causes long periods of delay while the background `cargo check` builds the entire dependency tree. Not ideal.

In the meantime I've used a workaround to create a new target directory, with the caveat that I have to create that directory manually and still have to do a `cargo build` before running tarpaulin if I've done a `cargo clean`.
```
cargo build
mkdir -p target/tarpaulin
cargo tarpaulin --target-dir target/tarpaulin ...
```

This puts the build artifacts in `target/tarpaulin/debug`.

I'd love a better way to do this. Setting `RUSTFLAGS` in the ALE configuration is ok, but the issue likely affects other workflows as well (since manual `cargo check` or `cargo test` is also affected). Perhaps tarpaulin could just use its own target directory? It already creates `target/tarpaulin` to store the `coverage.json` file.

**Comment by mathstuf** [comment]
> cargo tarpaulin --target-dir target/tarpaulin

Is this something that can be set up in `tarpaulin.toml`? Though a better default would be appreciated.

**Comment by colvinwellborn** [comment]
I had no luck with that. The build would fail, although I didn't really dig into why.

**Comment by xd009642** [comment]
Ah so `--target-dir` doesn't work if the directory doesn't exist so I'll add a fix for that. And every option that can be set via the command line args can be set via the `tarpaulin.toml` with the same name as the arg name.

As for changing the default target-dir I'm not 100% sold on that, for people who do run locally it could result in a lot more hard drive space used. Also, as long as it's easily configured I'm not sure how much gain this gives most users.

**Comment by colvin** [comment]
Fixing the `--target-dir` so it doesn't require an extra command would be a nice step.

Would `tarpaulin.toml` then look like this?

```
[tarpaulin]
target-dir = "target/tarpaulin"
```

It wasn't clear to me based on the documentation what the section header should be for top-level flags.

**Comment by xd009642** [comment]
Yeah that's fine, and section header name doesn't matter so much it's just a name for that specific configuration. You can give it a valid header name in toml that communicates what it gets coverage for. The only reserved name is `report` for how to report all the runs.

I've fixed the target dir and that's in develop if you want to try it earlier. There will probably be another release later this week

**Comment by colvin** [comment]
Thanks!

**Comment by mathstuf** [comment]
Even better would be if `CARGO_TARGET_DIR` could be used instead of a static `target` value in there. (Basically, replace a literal prefix `$CARGO_TARGET_DIR` with the appropriate value in this argument.)

**Comment by mathstuf** [comment]
> As for changing the default target-dir I'm not 100% sold on that, for people who do run locally it could result in a lot more hard drive space used.

Running `cargo update` is just as bad in general. I regularly find my `target` directories to be in the 3-4 GB range. As long as `cargo clean` finds and nukes these extra tarpaulin artifacts, that sounds good enough to me.

**Comment by mathstuf** [comment]
@colvin You should now be able to use the `CARGO_TARPAULIN_TARGET_DIR` in the next release to avoid the manual configuration.
