### ISSUE TITLE
Feature request: CLI arguments override config files

### ISSUE THREAD

**Issue by tonyfinn** [xd009642/tarpaulin#414]
It would be nice if I could override the config file on a per job run with a CLI argument. This is currently special cased for a small number of options, such as [`debug` and `verbose`](https://github.com/xd009642/tarpaulin/blob/master/src/config/mod.rs#L356), so these options provided on the CLI will override those specified in the config file, but other CLI options are ignored when a config file is present.

This would allow using the majority of settings from a config file while only overriding one or two on a per run basis. This would also bring tarpaulin in line with how inbuilt cargo commands treat config options, such as [`cargo build`](https://doc.rust-lang.org/cargo/reference/config.html#build)

The use case where this would be useful for me is to do with a project of mine where I have some [tarpaulin configuration](https://gitlab.com/tonyfinn/olympia/-/blob/master/.tarpaulin.toml) to run different sets of tests, as one set of tests must be run single threaded. I have this committed to the repo so that it also takes effect when local runs of tarpaulin are performed. 

In CI, I would like to also publish results to coveralls. Since I'm building on Gitlab CI, not Travis, I need to use a repo token, which I would like to not distribute in my repo, and instead provide it at runtime on the command line, [as seen in the test script here](https://gitlab.com/tonyfinn/olympia/-/blob/master/build/test.sh).

If you're ok with adjusting CLI options to work this way, I can submit a PR to make the change, it basically boils down to merging all CLI options, not just debug and verbose.

**Comment by xd009642** [comment]
So I had a certain number of CLI options override or extend the options from the config file based on what people would want to extend. If someone wants to extend someone and they can't via the options and it makes sense I'll happily accept the PR :smile:

**Comment by tonyfinn** [comment]
I've created a pull request to add this support to a few of the options I could see myself using, including the coveralls option I was looking for here: https://github.com/xd009642/tarpaulin/pull/419

I did not tackle any of the vec items, like the list of excluded files, packages, features, etc. The precendent set by the exclude option would be for options specified on the CLI to be additive to the options in the config file, but this then provides no way to exclude a normally included feature, or include a normally excluded file.

I can see three options for adding the ability to customize these multiple choice options in the CLI when a config file is present

1. Special case file inclusions to have an exclude and include option where the include option overrides the exclude option. This would allow something like `cargo tarpaulin --exclude tests/*.rs --include tests/test_utils.rs` or the same via mixed CLI/config file options. All other options,  being new, could then have CLI options replace existing config file options.
2. Update exclude to replace config file excludes and have all other multiple choice options do the same.
3. Have all options be additive and tell users that they need to have a second config file to have this kind of per-environment config.

Similarly, boolean flag options would then need to distinguish between default-true (like line-coverage) and default-false (like most of the options) and present/missing which would likely mean changing them all to Option<bool>, which would make all uses of the config values quite ugly in the rest of the codebase. The options without making it very messy there I can see there are:

1. Moving to accessor functions (like done for output_dir in the existing PR
2. Use a builder pattern for configs, where the `.build()` call populates default values for any booleans not set by then, so the rest of the code can use the built config and not worry about this.

Since the right option there isn't straightforward, and doesn't come under the use case I needed for at the start of the PR, I left making any changes to these options out of the initial PR. Let me know if you have any thoughts on how/if I should proceed for other options.

**Comment by xd009642** [comment]
There's an `--ignore-config` option which I figured would be enough for most overriding needs. There is a point where the behaviour in the config file and the extra options possibly become too much mental effort to interpret. 

I'll take a look at the PR hopefully tonight but if not tomorrow, initial glance on my phone looks good though :smile:

**Comment by xd009642** [comment]
A few more CLI args can now be overridden including:

In 0.13.0 released yesterday
* workspace
* packages

In some changes done today there's also now:
* frozen
* locked
* force-clean
* ignore-tests
* exclude

**Comment by xd009642** [comment]
Right I've gone through all the options. Now in develop everything is merged in some way apart from `--help`, `--version`, `--config <FILE>` and `--ignore-configs` the latter two are obviously ignored because they are used to select the active config. 

Here's a full list I was using to check things off as I did or verified them just for completeness.

- [x] --all-features           
- [x] --all-targets            
- [x] --benches                
- [x] --bins                   
- [x] --branch
- [x] --count                  
- [x] --debug                  
- [x] --doc
- [x] --dump-traces
- [x] --examples
- [x] --force-clean
- [x] --forward
- [x] --frozen
- [x] --help *Not applicable*
- [x] --ignore-config *Not applicable*
- [x] --ignore-panics
- [x] --ignore-tests
- [x] --ignored
- [x] --lib
- [x] --line
- [x] --locked
- [x] --no-default-features
- [x] --no-fail-fast
- [x] --no-run
- [x] --offline
- [x] --release
- [x] --tests
- [x] --version *Not applicable*
- [x] --verbose
- [x] --workspace
- [ ] -Z <FEATURES>...
- [x] --bench <NAME>...
- [x] --bin <NAME>...
- [x] --ciserver <SERVICE>
- [x] --config <FILE> *Not applicable*
- [x] --coveralls <KEY>
- [x] --example <NAME>...
- [x] --exclude <PACKAGE>...
- [x] --exclude-files <FILE>...
- [x] --features <FEATURES>...
- [x] --manifest-path <PATH>
- [x] --out <FMT>...
- [x] --output-dir <PATH>
- [x] --packages <PACKAGE>...
- [x] --profile <NAME>
- [x] --report-uri <URI>
- [x] --root <DIR>
- [x] --run-types <TYPE>...
- [x] --target <TRIPLE>
- [x] --target-dir <DIR>
- [x] --test <NAME>...
- [x] --timeout <SECONDS>
- [x] test executable args

**Comment by jaques-sam** [comment]
This is still an issue when specifying `engine = Llvm` on the command line (and maybe also for others).
The parameter is not taken into account... It's considered a bug and it has cost me some hours until I knew what the problem was!

The parameter seems to only work when adding it in the config file.

**Comment by xd009642** [comment]
You should specify `--engine llvm` and it will work. I'm pretty sure it works I do it most days. If you're having an issue with it open a new issue with details on your system project and extras l exact command and I'll look into it

**Comment by jaques-sam** [comment]
Yeah, I'm sorry. It doesn't work when I have a tarpaulin.toml config file in the repo. 
Why is `--engine` not in your list [here](https://github.com/xd009642/tarpaulin/issues/414#issuecomment-653753743) btw? 
I'll open an issue for that, probably next week.

**Comment by xd009642** [comment]
Because that list was made before it existed as an argument.
