### ISSUE TITLE
docker image xd009642/tarpaulin:latest is stale

### ISSUE THREAD

**Issue by Others** [xd009642/tarpaulin#518]
My instance of tarpaulin on CI has started complaining about my compile-fail tests. Here is an example [log](https://app.circleci.com/pipelines/github/Others/shredder/46/workflows/7b6f0001-bb44-4366-b198-ecb3942780f2/jobs/171).

I understand that these types of tests have an inherent flakiness to them, but they're useful for catching proc-macro bugs. Could the `xd009642/tarpaulin:latest` tag be updated to be built on the latest `rust` image?

**Comment by xd009642** [comment]
I've just triggered a rebuild in docker hub so once that job is processed it should be up. It's a bit of a pain because it's the latest rust version at the time the image is built and for subsequent updates I have to retrigger it. If you have any docker hub tips to solve this it would be appreciated. However, I'm not holding my hopes too high docker hub often spuriously fails to build without giving any logs...

**Comment by xd009642** [comment]
Well the builds all completed successfully so all the tagged builds (including latest) are now using the latest rust base image

**Comment by Others** [comment]
Yep my issue is resolved! Thanks for your help
