### ISSUE TITLE
Fail on minimum coverage threshold not being met

### ISSUE THREAD

**Issue by Dandandan** [xd009642/tarpaulin#521]
For example in pytest-cov `--cov-fail-under 50` fails under 50% total coverage.
This makes it easy to set it as rule in a CI pipeline.

**Comment by xd009642** [comment]
Yeah makes sense as a feature, I'd probably name it `--fail-under` personally instead of copying pytest. 

I'm not sure if I'll have time to look at tarpaulin until later in the week and I have some other things in progress but I might get to it during the weekend. Otherwise, I'd happily mentor anyone who wanted to do a PR.

**Comment by xd009642** [comment]
I started implementing this but it's gonna need slightly more thought based on how it should act if defined differently for multiple configs. 

My current thought is that it's applied locally on each config it's defined on and if on the default (CLI arg generated) or report config then applied globally. But then if it falls under threshold on a local config should also run all others instead of exiting early imo. I'll hopefully finish it off tomorrow after work

**Comment by Dandandan** [comment]
Thanks a lot, awesome @xd009642 !
