### ISSUE TITLE
Future of unstable/nightly support?

### ISSUE THREAD

**Issue by johnoneil** [xd009642/tarpaulin#762]
**Question: Unstable features will require Rust nightly for how long?**

We've started using Tarpaulin for coverage metrics as it's plainly the current best solution, but we are worried about having to use a nightly build of Rust to get unstable features. Is there any roadmap for stabilizing these features and supporting Rust relases?

Any info is appreciated. Nightly releases of Rust are somewhat spotty (often with missing components) so we're pinned on a specific (working) version, but it's plainly not a desirable situation.

**Comment by xd009642** [comment]
So the only nightly only feature currently is doc test coverage, and that's because it relies on an unstable rustdoc flag to stop cargo test from deleting them after it's built and run them. Unfortunately, I don't have the means to stabilise that myself or the recent --no-run flag for doc tests. Everything else works fine on stable. 

At some point when the llvm coverage support is integrated there will be a different coverage collection method when tarpaulin runs in nightly versus stable but nightly won't be required and for existing users it won't be visible with current usage (except for the results should become more accurate).

**Comment by johnoneil** [comment]
Thanks @xd009642  appreciate your info.
Ironically Doctest coverage is exactly the functionality we're interested in.
We'll keep an eye on further developments. Closing this question.
