### ISSUE TITLE
Verbose flag does not display more info

### ISSUE THREAD

**Issue by ralpha** [xd009642/tarpaulin#787]
When using `cargo tarpaulin --verbose` it does not display much more info then when I leave the flag off.
This might be a bug or it might not pass the `--verbose` flag to cargo itself while building/testing the application/library.

**Comment by xd009642** [comment]
Ah this is because I originally had `--verbose` pass `-vvv` into cargo, but changed that to happen `--debug` is passed as it was just too much info. But yeah `--verbose` should result in a `-v` to cargo and maybe some of the  `trace!` calls in the code would be more suitable as `debug!`. I'll either get to this tonight or I'll accept PRs ofc :+1:

**Comment by xd009642** [comment]
I've just pushed a commit that passes the verbose flag to cargo if verbose is set. I'll have a look at some of the other logs at some point and close this issue after I've done that

**Comment by xd009642** [comment]
Oh with the latest release cargo will get a `-v` when there's `--verbose` so gonna close this

**Comment by ralpha** [comment]
@xd009642 Thank you for fixing this. This helped my narrow down the problem I had with #517.
Also thanks for the very quick response! (although I did not replay that quickly myself)

Thanks for making this awesome crate. :heart:
