### ISSUE TITLE
Tarpaulin fails with `Error: time: cannot find attribute `skip` in this scope`

### ISSUE THREAD

**Issue by PoignardAzur** [xd009642/tarpaulin#830]
**Describe the bug**

When running `cargo tarpaulin` on the 
[druid](https://github.com/linebender/druid)
repository, I get the following error:

```
    Compiling time-macros v0.1.0
error: Broken pipe (os error 32)
error: build failed
Sep 14 12:22:53.709 ERROR cargo_tarpaulin: Failed to compile tests! Error: time: cannot find attribute `skip` in this scope
Error: "Failed to compile tests! Error: time: cannot find attribute `skip` in this scope"
```

This is similar to #756; but the main difference is that the offending crate seems to be `time-macros`.

A workaround is to compile with `cargo tarpaulin --avoid-cfg-tarpaulin`, which compiles and runs the tests and outputs a coverage report; but it's not clear to me why that flag is necessary. At the very least, if it's the intended solution, an error message should suggest using it.

**Versions**

```
> cargo tarpaulin --version 
cargo-tarpaulin version: 0.18.2
> cargo --version
cargo 1.54.0 (5ae8d74b3 2021-06-22)
> rustc --version
rustc 1.54.0 (a178d0322 2021-07-26)
```

Druid commit hash: **c93a7c4a48ff8e69516813a7467e8ae9edea0846**.

**Comment by xd009642** [comment]
Wow that's an old version of time-macros, the new one should fix it so if you can update that would be preferrable. 

Also a reason I haven't printed out the suggestion is because that error comes from Cargo/rustc and it does kinda rely on the error message being stable between versions and there not being another macro called skip that causes an issue. I'll do a PR to add a suggestion printout though this evening - or will happily accept one if you can't wait till then

**Comment by PoignardAzur** [comment]
Alright, I'll try to update the dependencies. Thanks.

**Comment by PoignardAzur** [comment]
It works.
