### ISSUE TITLE
Duplicated RUSTFLAGS

### ISSUE THREAD

**Issue by orenbenkiki** [xd009642/tarpaulin#891]
**Description:** naively setting `RUSTFLAGS` always triggers recompilation, even if set to exactly what is used by `tarpaulin`.

**To reproduce:**

1. Tarpaulin uses different RUSTFLAGS than the default. To ensure that `cargo check`, `cargo test`, `cargo clippy` etc. use the same flags I did:

```
echo '[build]' > .cargo/config.toml
cargo tarpaulin --print-rust-flags | tail -1 | sed 's/RUSTFLAGS/rustflags/' >> .cargo.toml
```

2. I then built and tested the project using `cargo test`.

3. I then invoked `cargo tarpaulin --skip-clean`.

**Expected** : the currently built project will be used without compiling anything.

**Actual**: everything got rebuilt.

**Workaround**: Between steps 2 and 3, do `rm .cargo/config.toml` - now nothing will be rebuilt as expected.

It seems as though tarpaulin adds its flags to `RUSTFLAGS` on top of whetever is in `cargo.toml`, even if the flags are duplicated. On it face, this should't matter, but it seems `cargo` isn't clever enough to figure out that specifying the same flag twice makes no difference, so it thinks this is a different configuration and rebuilds everything.

**Solution(?)**: `tarpaulin` should avoid adding a duplicate of a flag that already exists in `RUSTFLAGS`, so that placing the correct set of flags in `cargo.toml` will behave as expected.

**Comment by xd009642** [comment]
I've created a PR for this if you want to check it behaves as anticipated regarding the rebuilds (I'll also check it later just have other things to do right now)

**Comment by orenbenkiki** [comment]
Wow, thanks for the quick response and coding!

Looking at the PR code, it isn't clear to me why you de-duplicate based only on the flag name ignoring the value. That is, it seems from the code that if for some reason `RUSTFLAGS` contains `-Cfoo=1 -Cfoo=2`, then you'd only include the 1st one (`-Cfoo=1`).

If keeping only one value makes sense, shouldn't it be the last, rather than the 1st? This can be achieved by reversing the iteration order on the flags - possibly collect into a vector and reverse it in the end to preserve the overall order, if that is significant.

But - wouldn't it be better (it would certainly be simpler) to just de-dup on the complete parameter (both name and value), so in such a case both occurrences would survive?

**Comment by xd009642** [comment]
I don't think there's any cases with a `-C` or `-Z` flag where having two with different values is well-defined i.e. -Cdebuginfo can't be defined twice with two values. Although, it may be there's flags that makes sense for, in which case I'd need to reconsider the approach. 

As for why I take the first, that's so the parameters I want to set for tarpaulin don't get overridden by things in the .cargo/config or environment variable supplied rust-flags. There are flags/value combinations that remove useful information tarpaulin needs, i.e. if we took `-Cdebuginfo=0` there would be no way to map from instructions to source locations (in fact removing user attempts to override that flag was already implemented in tarpaulin because of a previous issue).

**Comment by orenbenkiki** [comment]
Definitely tarpaulin should override the RUSTFLAGS - I just thought that the tarpaulin flags were added at the end rather than at the front of the existing RUSTFLAGS; In general I tend to think of flags as last-one-wins. I guess if you add them at the front than having the 1st one win also works.

Thanks!
