### ISSUE TITLE
coveralls.io doesn't display/render source files

### ISSUE THREAD

**Issue by SirDoctors** [xd009642/tarpaulin#9]
This is seen with this build for keygraph-rs.
![coveralls](https://user-images.githubusercontent.com/7450443/28484888-27661d74-6e43-11e7-9bd4-be977ed5a13e.PNG)
If you look closely at it, you can see that the filename while listed as ``src/lib.rs``, coveralls is looking for ``src/src/lib.rs``
![coveralls 2](https://user-images.githubusercontent.com/7450443/28484934-8f2063c0-6e43-11e7-9c7a-48f51fca1feb.PNG)

**Comment by xd009642** [comment]
That was my fault with the initial kcov setup, it put the file names but not paths in so I added the path prefix manually. The coveralls-api crate when it submits the report puts the path relative to the cargo manifest (because a project might have multiple files called mod.rs) so this prefix became unnecessary.

I've removed the prefix and the source now shows up!
